TEX := cj2003 \
       abstract \
       introduction \
       presentation \
       core_asn1 \
       well_founded_types \
       constraints \
       constraints_from_types \
       constraints_from_subtypes \
       full_collection_and_solving \
       conclusion

BIB := cj2003
