TEX := unpar \
       cpp \
       abstract \
       introduction \
       model \
       backtracking \
       backtracking_soundness \
       backtracking_completeness \
       backtracking_determinacy \
       es1 \
       es1_soundness \
       es1_completeness \
       es1_worst \
       f0 \
       f0_soundness \
       implementation \
       related_work \
       conclusion \
       appendix \
       minimality

BIB := unpar

USE_PS := yes
